server:
  port: 8080

spring:
  application:
    name: EDGE-SERVICE

zuul:
  routes:
    ITEM-SERVICE:
      path: /items/**
      serviceId: ITEM-SERVICE
      stripPrefix: false
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      ITEM-SERVICE:
      - limit: 10
        refresh-interval: 30

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
