server:
  port: 8081

spring:
  application:
    name: ITEM-SERVICE

logging: #Make sure to change the path /Users/mukeshkumar/development/logs as per your system.
  file: /Users/mukeshkumar/development/logs/item-service.log

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"